FROM continuumio/miniconda3

MAINTAINER Gilles Bodart <gillesbodart@users.noreply.github.com>

# Clone
WORKDIR /app
RUN git clone https://github.com/facebookresearch/LASER.git

# Set workdir
ENV LASER /app/LASER
WORKDIR $LASER
RUN ls $LASER

# Replace scripts
COPY ./download_models.sh /app/LASER/nllb
COPY ./embed.sh $LASER/tasks/embed/

# Download LASER from FB
RUN bash ./install_models.sh
# RUN bash ./nllb/download_models.sh tat_Cyrl bak_Cyrl kaz_Cyrl khk_Cyrl kir_Cyrl tgk_Cyrl tur_Latn azj_Latn tuk_Latn uzn_Latn
RUN bash ./nllb/download_models.sh tat_Cyrl

# Install dependencies
RUN conda create -n env python=3.7
RUN echo "source activate env" > ~/.bashrc
ENV PATH /opt/conda/envs/env/bin:$PATH

RUN apt-get -qq -y update
RUN apt-get -qq -y upgrade
RUN apt-get -qq -y install \
        gcc \
        g++ \
        wget \
        curl \
        git \
        make \
        unzip \
        sudo \
        vim \
        cmake

# Use C.UTF-8 locale to avoid issues with ASCII encoding
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY ./requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt --verbose

#Installing FAISS

RUN conda install --name env -c pytorch faiss-cpu -y

RUN bash ./install_external_tools.sh

COPY ./decode.py $LASER/tasks/embed/decode.py

# Make port 80 available to the world outside this container
WORKDIR /app

RUN echo "Hello World" > test.txt

RUN $LASER/tasks/embed/embed.sh test.txt test_embed.raw
RUN python $LASER/tasks/embed/decode.py test_embed.raw

#Open the port 80
EXPOSE 80

COPY ./app.py /app/app.py
RUN touch /app/LASER/source/lib/__init__.py

CMD ["/bin/bash"]
